
spring:
  application:
    name: Config-Default-Profile
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RushiKadam08/HotelManagement-Config_Server
          clone-on-start: true


